#!/usr/bin/env bash
# Lamplight Install Script
# Run this once from the project root to make 'lamplight' available globally

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAMPLIGHT_BIN="$SCRIPT_DIR/bin/lamplight"

# Color output
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
RED=$'\e[31m'
CYAN=$'\e[36m'
NC=$'\e[0m'

echo -e "${CYAN}╔════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     Lamplight Installer            ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════╝${NC}"
echo

# Check if lamplight binary exists
if [[ ! -f "$LAMPLIGHT_BIN" ]]; then
  echo -e "${RED}Error: bin/lamplight not found.${NC}"
  echo "Please run this script from the Lamplight project root."
  exit 1
fi

# Determine install location
# Prefer ~/.local/bin (user-local, no sudo needed)
# Fall back to /usr/local/bin if user prefers system-wide
USER_BIN="$HOME/.local/bin"
SYSTEM_BIN="/usr/local/bin"

echo -e "${YELLOW}Where would you like to install lamplight?${NC}"
echo -e "  ${GREEN}1${NC}) $USER_BIN (recommended, no sudo required)"
echo -e "  ${GREEN}2${NC}) $SYSTEM_BIN (system-wide, requires sudo)"
echo -e "  ${GREEN}3${NC}) Custom path"
echo -n "Select [1]: "
read -r choice

INSTALL_DIR="$USER_BIN"
USE_SUDO=""

case "$choice" in
  2)
    INSTALL_DIR="$SYSTEM_BIN"
    USE_SUDO="sudo"
    ;;
  3)
    echo -n "Enter custom path: "
    read -r custom_path
    INSTALL_DIR="$custom_path"
    # Check if we need sudo for custom path
    if [[ ! -w "$INSTALL_DIR" ]] && [[ -d "$INSTALL_DIR" ]]; then
      USE_SUDO="sudo"
    fi
    ;;
  *)
    INSTALL_DIR="$USER_BIN"
    ;;
esac

# Create directory if it doesn't exist
if [[ ! -d "$INSTALL_DIR" ]]; then
  echo -e "Creating directory: ${CYAN}$INSTALL_DIR${NC}"
  $USE_SUDO mkdir -p "$INSTALL_DIR"
fi

# Create the wrapper script (resolves to absolute path)
WRAPPER="$INSTALL_DIR/lamplight"

echo -e "Installing to: ${CYAN}$WRAPPER${NC}"

$USE_SUDO tee "$WRAPPER" > /dev/null << EOF
#!/usr/bin/env bash
# Lamplight launcher - auto-generated by install.sh
exec "$LAMPLIGHT_BIN" "\$@"
EOF

$USE_SUDO chmod +x "$WRAPPER"

# Check if install directory is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
  echo
  echo -e "${YELLOW}Note:${NC} $INSTALL_DIR is not in your PATH."
  echo -e "Add this line to your ${CYAN}~/.bashrc${NC} or ${CYAN}~/.zshrc${NC}:"
  echo
  echo -e "  ${GREEN}export PATH=\"\$PATH:$INSTALL_DIR\"${NC}"
  echo
  
  # Offer to add it automatically
  echo -n "Add to shell config automatically? [Y/n]: "
  read -r add_path
  
  if [[ ! "$add_path" =~ ^[Nn]$ ]]; then
    SHELL_RC=""
    if [[ -f "$HOME/.zshrc" ]]; then
      SHELL_RC="$HOME/.zshrc"
    elif [[ -f "$HOME/.bashrc" ]]; then
      SHELL_RC="$HOME/.bashrc"
    fi
    
    if [[ -n "$SHELL_RC" ]]; then
      echo "" >> "$SHELL_RC"
      echo "# Lamplight" >> "$SHELL_RC"
      echo "export PATH=\"\$PATH:$INSTALL_DIR\"" >> "$SHELL_RC"
      echo -e "${GREEN}✔${NC} Added to $SHELL_RC"
      echo -e "Run ${CYAN}source $SHELL_RC${NC} or open a new terminal."
    else
      echo -e "${YELLOW}Could not detect shell config file.${NC}"
      echo "Please add the PATH export manually."
    fi
  fi
fi

echo
echo -e "${GREEN}✔ Lamplight installed successfully!${NC}"
echo
echo -e "Run ${CYAN}lamplight${NC} from any terminal to start."
echo -e "To uninstall, simply delete: ${CYAN}$WRAPPER${NC}"
